### ISSUE TITLE
 ORIPA S gets slow for a massive data

### ISSUE THREAD

**Issue by rschamp** [oripa/oripa#1]
_Issue by **[Ooouch1](https://github.com/Ooouch1)** from Monday Feb 11, 2013 at 10:48 GMT_
_Originally opened as https://github.com/Ooouch1/oripaS/issues/1_

---

It is a  problem of implementation and computational time rather than a bug but is considerable issue for user experience.

**Comment by Ooouch1** [comment]
I fixed it while refactoring in remove_global branch.
