### ISSUE TITLE
Input lines by "view crossline" on the folded model

### ISSUE THREAD

**Issue by rschamp** [oripa/oripa#10]

**Comment by Ooouch1** [comment]
This operation on a flap can be achieved with combination of adding a point, adding a line, and suggesting line. Line suggestion is more powerful because it also determines mountain/valley.
I believe folding a whole of model with a certain line is not what we want in many cases.

**Comment by Ooouch1** [comment]
I'll close this issue.
If you need this functionality, open new issue with detailed requirements.
