### ISSUE TITLE
Can't launch the app.

### ISSUE THREAD

**Issue by nkint** [oripa/oripa#125]
Hi!

Sorry for my dumb question but I'm new to java.
And honestly I don't want to take journey into java, I just want to open some .opx files I found in [this repository](https://github.com/rschamp/schamp-origami) and convert them to .svg.

I have downloaded java, and the ORIPA app from this [release link](https://github.com/oripa/oripa/releases/download/v1.50_release/oripa-1.50.jar).

If I try to run the command:

```sh
$ java ./oripa-1.50.jar
```

I get the error:
```
Error: Could not find or load main class ..oripa-1.50.jar
Caused by: java.lang.ClassNotFoundException: //oripa-1/50/jar
```

NOTE:
```sh
$ java --version

java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

Again, thanks, hope not to bother you.

**Comment by Ooouch1** [comment]
Try
`$ java -jar ./oripa-1.50.jar`

**Comment by nkint** [comment]
It works like a charm, thanks!
