### ISSUE TITLE
Memo TextArea not displaying long lines correctly

### ISSUE THREAD

**Issue by lifesbest23** [oripa/oripa#161]
While testing #160 I found long lines in the `JTextArea` for the memo field in the `PropertyDialog` to disappear on the side without adding a scrollbar or line wraps.

I would add full word line wraps as well as a vertical scroll bar to the TextArea.

In addition to that I would also refactor `AbstractPropertyDialog` to use String resources, `GridBagConstraintsBuilder` and the overall code structure.

**Comment by lifesbest23** [comment]
Not sure if my string resources are descriptive enough.

Also I would like to ask if I should further combine `PropertyDialog` as really simple implementation of the `AbstractPropertyDialog`? For me this abstraction would only make sense if there are several different types of Property windows, for different File Types.

**Comment by Ooouch1** [comment]
> Not sure if my string resources are descriptive enough.

Personally I'm not familiar with the abbreviation "DIAL" for "DIALOG". I think "PROP" is OK because I found it in an online dictionary.

In the label resource, I suggest "File Author" instead of "Editor data", which is used in FOLD format.
Other words sound correct.

> Also I would like to ask if I should further combine PropertyDialog as really simple implementation of the AbstractPropertyDialog? For me this abstraction would only make sense if there are several different types of Property windows, for different File Types.

I agree with you. Simplification is welcome.

**Comment by lifesbest23** [comment]
Implemented your suggestions, everything should be fine now.
