### ISSUE TITLE
Updating Dependencies

### ISSUE THREAD

**Issue by lifesbest23** [oripa/oripa#168]
While fixing the issue with the dependabot (#166), that was present for a while, I came across the other maven dependencies, that are all pretty old. Should we update them at some point? I would not see any benefits nor problems with that, even though I have not looked at the changes that would come with updating them.

**Comment by Ooouch1** [comment]
I googled and found that the latest version of slf4j is 2.0 (alpha) and its new API might be more comfortable to use. However, I think we don't have to hurry to update because fatal bugs of those old plugins are not reported. I don't like API of vecmath but replacing is tough.

**Comment by lifesbest23** [comment]
Ok, so they would remain at their current versions for now unless there is a need for updating them.

> I don't like API of vecmath but replacing is tough.

Is there a preferred alternative?

**Comment by Ooouch1** [comment]
I like immutability of Vector in Apache Commons Math. The library contains many components that won't be needed in ORIPA, though.
