### ISSUE TITLE
Erasing vertex automatically after deleting selected lines

### ISSUE THREAD

**Issue by rschamp** [oripa/oripa#2]
_Issue by **[Ooouch1](https://github.com/Ooouch1)** from Monday Feb 11, 2013 at 10:53 GMT_
_Originally opened as https://github.com/Ooouch1/oripaS/issues/2_

---

Requested by Rowin on my blog.
Remaining points can be annoying.

**Comment by Ooouch1** [comment]
Seems done at some version.
