### ISSUE TITLE
Bug in solver?

### ISSUE THREAD

**Issue by origamimagiro** [oripa/oripa#233]
There may be a bug in the folded-state solver for Full Estimation? ORIPA finds 625 Answers for the attached crease pattern (credit [Dan Brown](https://www.flickr.com/photos/danielbrown/)). However, both Oriedita and flat-folder find 20,736 valid flat-foldable states, one of which is the desired state for this color-change model which ORIPA does not find. Hopefully this example can be a useful test case for improving the ORIPA solver.

[A23.zip](https://github.com/oripa/oripa/files/10417984/A23.zip)

**Comment by Ooouch1** [comment]
Thank you for reporting.

I tested on ver.0.36 and ver.1.62, and both reproduce the problem. 
Some essential part might be wrong...

**Comment by Ooouch1** [comment]
Simplified CP that still produces the problem is attached.
[A23_partial.zip](https://github.com/oripa/oripa/files/10419573/A23_partial.zip)

**Comment by Ooouch1** [comment]
Probably fixed.
