### ISSUE TITLE
Invalid solutions for unassigned CP

### ISSUE THREAD

**Issue by OrigamiDraw** [oripa/oripa#282]
I found an unassigned CP that causes problem. Release #1.66 gives 10 possible folded states, while Flat-Folder only gives 8. I think solutions #1 and #10 cause self-intersection. The folded model contains a cell where all 6 faces overlap, so the faces should be in an acyclic order, which is not possible with the corresponding ORMATs. The CP is attached in FOLD format (but with suffix .txt for GitHub) and SVG. The two Excel files show the two invalid solutions. Faces are labeled "A" through "F".

[unassigned_hex_hat.fold.txt](https://github.com/oripa/oripa/files/11650447/unassigned_hex_hat.fold.txt)
[unassigned_hex_hat.ormat.10.xlsx](https://github.com/oripa/oripa/files/11650427/unassigned_hex_hat.ormat.10.xlsx)
[unassigned_hex_hat.ormat.1.xlsx](https://github.com/oripa/oripa/files/11650428/unassigned_hex_hat.ormat.1.xlsx)
![unassigned_hex_hat](https://github.com/oripa/oripa/assets/110136377/fca271de-a2f2-4ed5-919d-10820b85442d)

**Comment by OrigamiDraw** [comment]
Indeed. And No. 10 is simply the same with all the folds flipped. So, this bug could happen for oriented CPs as well.
![assigned_hex_hat_unfoldable](https://github.com/oripa/oripa/assets/110136377/f8463c24-1d65-4516-a70a-0c764bdd5eb2)
![assigned_hex_hat_unfoldable2](https://github.com/oripa/oripa/assets/110136377/eb527f3a-58b9-46c0-8755-469be0d4e4ae)

**Comment by Ooouch1** [comment]
fixed version is released.

**Comment by OrigamiDraw** [comment]
Amazing: this bug seems to have been there from the very beginning. I tested as far back as version 0.36.
This fix works but I wish we could avoid going through all the transitivity constraints again. I don't know if that is possible with the overall algorithm.
