### ISSUE TITLE
Introduce more origami-like input method

### ISSUE THREAD

**Issue by rschamp** [oripa/oripa#4]
_Issue by **[Ooouch1](https://github.com/Ooouch1)** from Sunday Jun 30, 2013 at 15:25 GMT_
_Originally opened as https://github.com/Ooouch1/oripaS/issues/5_

---

Conventional input is familiar to mathematical definition.
In origami, we often fold "Point to Point", "Line to Line" and so on.
(or we often use the folds 1 to 4 claimed in Origami Axiom.)

**Comment by Ooouch1** [comment]
Axiom 1 to 4 are implemented now. And this is partial duplication of #9
