### ISSUE TITLE
Colinear lines are not split properly

### ISSUE THREAD

**Issue by undertrox** [oripa/oripa#41]
Lines that do not cross in a single point, but that are parallel and overlap, are not split properly.

**Steps to reproduce:**
 - draw a diagonal line from the top left corner 3/4 of the way down
 - draw a diagonal line from the bottom right corner 3/4 of the way up
 - the check window will show this:
    
![check window error](https://user-images.githubusercontent.com/20705949/93126186-5a7b1b00-f6cc-11ea-9cc2-2f4f29c83fa0.png)

**Comment by Ooouch1** [comment]
I reproduced the case in ver. 1.10, and I see that the first line is not split by the second line's vertex.
In my opinion, this is an invalid input, not a bug. I think managing overlaps of lines is user's responsibility.
Splitting is not enough to correct the invalid input (we will have two overlapping lines on the center), and, generally speaking, the code tends to be messy if we try to correct an invalid input.

I'm not positive to make a change on the code for this issue...

**Comment by undertrox** [comment]
I can see that. However, it's not clear at all to the user that this is invalid input, and I know of many instances where people were confused why their cps weren't flatfoldable. In this example, it was obvious that no one should do this, but if you consider this cp for example:
<img src="https://user-images.githubusercontent.com/20705949/93259820-bfa04080-f7a0-11ea-8687-176692f306b3.png" height="500px"></img>
it seems logical to draw a diagonal line from bottom right to top left, but doing that would create the same issue

I would suggest to either highlight overlapping lines in the check window, or disallow this kind of invalid input entirely.

**Comment by Ooouch1** [comment]
Good suggestion.
It seems easy to highlight overlapping lines in the check window.
I'll consider in the next version of ORIPA.

Thank you.
