### ISSUE TITLE
Remove java3d dependency

### ISSUE THREAD

**Issue by Ooouch1** [oripa/oripa#48]
java3d is a dead project. What we really need is Vector2d (and Vector3d in some places) of javax.vecmath (https://mvnrepository.com/artifact/javax.vecmath/vecmath/1.5.2). However, javax.vecmath  also seems a dead project.
It is a tough work to replace vecmath's Vector2d/Vector3d with plain-old-java-objects but that's what we should do.

**Comment by gkonjevod** [comment]
Is java3d dead? Version 1.7 was released last February, and here's a discussion arguing it is just moving slowly: https://jvm-gaming.org/t/is-java3d-dead-and-what-are-the-alternatives/24281 
The same thread also offers some alternatives, but I know nothing about them. 

I haven't really been active with this project, but thank you for keeping it moving!

**Comment by Ooouch1** [comment]
I would like to manage dependencies by Maven. Unfortunately the Maven's repository doesn't include the latest java3d. As I mentioned, our usage of java3d is very limited and therefore importing whole of java3d is overkill.

Thank you for your response.

**Comment by gkonjevod** [comment]
I see---those are both valid reasons to look for a replacement or reimplement what's needed. Thank you.

**Comment by Ooouch1** [comment]
Vector2d is reimplemented in #300 .
