### ISSUE TITLE
Make antialiasing configurable

### ISSUE THREAD

**Issue by undertrox** [oripa/oripa#50]
With more complex cps, the added line thickness from antialiasing can sometimes be annoying, so it'd be nice to have an option to turn it off

Since there isn't really a settings window, the best option might be to put a checkbox somewhere for toggling antialiasing

**Comment by Ooouch1** [comment]
Hmm... Considerable. It might be included in v1.30.
Thank you for your suggestion.

**Comment by Ooouch1** [comment]
Done.
