### ISSUE TITLE
Delete Function doesn't always delete all Lines

### ISSUE THREAD

**Issue by undertrox** [oripa/oripa#59]
Sometimes, deleting multiple lines at once by dragging in delete mode leaves some lines in the box behind. It seems to happen when two straight crossing lines are removed at once, but even then, it doesn't happen with every configuration. Here is an example of a line configuration where the bug appears for me:
![grafik](https://user-images.githubusercontent.com/20705949/100146565-650b1b00-2e9a-11eb-99ea-7ecc3a5059b1.png)
This is what it looks like after deleting:
![grafik](https://user-images.githubusercontent.com/20705949/100146624-7eac6280-2e9a-11eb-942b-9489ac77bc4f.png)
I suspect that this happens because deleting 2 of the lines first merges the other 2 lines, creating a new line that then isn't in the "to be deleted" list, but I'm not sure.

**Comment by Ooouch1** [comment]
Maybe you are right. I'll fix it.
