### ISSUE TITLE
UIPanel rework

### ISSUE THREAD

**Issue by lifesbest23** [oripa/oripa#76]
In my forked repository I am almost finished with a small UIPanel rework to make easier to add new features to it, I am not sure If this is something desirable but I for adding more display settings or even more detailed tooltips a flexible Panel design might be more comfortable.
It is the [https://github.com/lifesbest23/oripa/tree/restructure](url) branch if you want to take a look.
Don't want to create a pull request yet as I would be interested if that is something you would like to see?

**Comment by Ooouch1** [comment]
I read the new UIPanel.java and GridBagFactory.java.
Your UIPanel.java is more readable.
Mutability of GridBagFactory (gridX and gridY) is slightly different from the usual Factory pattern (I expect factories to be immutable) but I think it's effective in this case.

Nice work.

**Comment by lifesbest23** [comment]
You are right that it does not follow a classical Factory scheme, renamed it now to GridBagConstraintsBuilder as I think that it is less misleading and added some javadoc to it.

**Comment by Ooouch1** [comment]
Good.

**Comment by Ooouch1** [comment]
@lifesbest23 I noticed it would be better to rename the instance name `gbFactory` to `gbBuilder`. The change for #66 on UIPanel seems deleted: I added TypeForChange.AUX and TypeForChange.CUT to alterLine_comboData_from.

**Comment by lifesbest23** [comment]
Finally came around to adding the two entries I missed in the last merge. Also merged your new changes to my branch, I would make a pull request for v1.40 now, if you would want the UI changes in this branch.
I did not thoroughly test everything but for me it seems to work well.

**Comment by Ooouch1** [comment]
I like your modification on UI. Please make a pull request.
By the way, I think gbBuilder.weightX and gbBuilder.weightY can be private. (You changed them public for debugging, right?)

**Comment by lifesbest23** [comment]
Yes, my weird bounds check for the double values seemed to not have worked correctly.

**Comment by Ooouch1** [comment]
Done.
