### ISSUE TITLE
File dialog doesn't open the last directory on Mac

### ISSUE THREAD

**Issue by Ooouch1** [oripa/oripa#83]
I heard it from a Mac user. (I don't have Mac.)
It seems a file path problem and might be solved by using File.getCanonicalPath().

**Comment by rschamp** [comment]
I haven't seen this issue with File->Open, but this does exist for File -> Export. Exporting always opens to the home directory, rather than the last place you exported to.  This problem still exists in 1.45 after 75f2a1b.

**Comment by Ooouch1** [comment]
I'm glad if you fix it.

**Comment by rschamp** [comment]
I will try!

**Comment by Ooouch1** [comment]
I had a glance at the code and noticed that "Export XXX" of the main frame uses saveUsingGUIWithModelCheck() which doesn't receive the last directory's path. This is not Mac specific.

**Comment by Ooouch1** [comment]
Since this problem is not Mac specific, I will fix it.
