### ISSUE TITLE
Setting up automated builds

### ISSUE THREAD

**Issue by rschamp** [oripa/oripa#84]
Curious if you would be interested in trying out using GitHub Actions to automatically run maven so tests and builds would be available for each commit pushed to master and pull requests?  Not talking about automatically releasing, just making  the build artifacts available. If so I'd be happy to try to set that up.

**Comment by rschamp** [comment]
Only thought of this because I was going to check out the fix for #83 — it's easy enough to check out the commit locally but would be even easier if I could download it directly from GitHub :)

**Comment by Ooouch1** [comment]
Sounds good. I would like you to do that.
