### ISSUE TITLE
FOLD-Export is slow for complex cps

### ISSUE THREAD

**Issue by undertrox** [oripa/oripa#94]
I tried exporting the CP of Kota Imai's Japanese Spiny Lobster as .fold, but it's very slow. It took 15 minutes to export. I understand that this cp might be more complex than what oripa was designed for, but saving normally just takes a few seconds, so I think it should be possible to reduce the exporting time to seconds instead of minutes at least. 

If that's not possible, I think there should be at least a warning when you try to export a cp with more than x lines, so you don't lose progress by oripa locking up trying to export

**Comment by Ooouch1** [comment]
Thank you for reporting. I will try to improve the conversion algorithm.
