### ISSUE TITLE
Adding SVG export for the origami model, in addition to the obj export

### ISSUE THREAD

**Issue by JinoBetti** [oripa/oripa#96]
I added this new functionality, but I'm not familiar with github forks and pull requests yet, so I don't now how I can share it so that it might be integrated in a future version: for now I forked it and pushed to my fork and I'll try making a pull request after that.

I also refactored all svg exports, implementing svg functions to generate lines and paths without having to handle them manually each time, etc... 

Feel free to comment and tell me if the functionality seems useful and if it could be integrated in the next version (I kind of used it before, but I used the OBJ export and made a converter program to convert the obj file into the SVG, so I think this can be useful)

**Comment by Ooouch1** [comment]
I'm happy that you are interested in this project. As I mentioned in your pull request, SVG export of folded model is broken in your version. Your new functionality will be merged into the next version if the bug is fixed.
