### ISSUE TITLE
Lines may not be divided correctly due to approximations

### ISSUE THREAD

**Issue by JinoBetti** [oripa/oripa#98]
**Minimal Test Case** : 
Activate any grid (the basic 4x4 grid works fine)
Draw a diagonal Line from point (-200,-200) to point (200,200)
Draw an horizontal line from point (0,200) to (0,0)

**Expected result** : The diagonal line should be divided into two lines, since the point (0,0) is on the line.

**Result** : The diagonal is not divided

**Workaround** : draw a line that's longer than needed and delete the excess afterwards

**Analysis** : The calculation of wether the line should be divided or not is made by the `RectangleClipper` class, called from the `LineAdder::addAll` method
This class builds a rectangle around the newly added line to do the clipping, adding a slight amount to each coordinates (`POINT_EPS = 1.0E-5`), to avoid problems due to approximations in calculations (?)
then, the `clipTest` method of `RectangleClipper` returns `false`, but should return `true`.
This seems to be due to approximations made in the `calcClippedPoint` method.
If I understand correctly, we calculate the `y` coordinate on the diagonal, for the `m_minX` (`=-1.0E-5`) abscissa... the result should be the same, since this is a diagonal, but the approximations made by the calculation brings a value of `-1.0000000003174137E-5`, which is unfortunately outside of the clipping rectangle...

**Possible solutions** : 
- The approximation goes clearly too far and could be considered equal to `-1.0E-5`
- Instead of testing the affine function at the `m_minX` abcsissa, we could test it at `m_minX + POINT_EPS`, which is the coordinate that should really be tested (I think this would be a cleaner solution mathematically speaking, since it really is the point we input in the first place. The small epsilon that has been added before is still relevant and should still be in the `if ((cy >= m_minY) && (cy <= m_maxY))` test)

**Comment by JinoBetti** [comment]
plus I think it is a little confusing to have two different values of epsilons in the RectangleClipper class : the one in the constuctor (which is actually POINT_EPS) and the EPS constant in the class.

Wouldn't it be easier to consider both lines as affine functions, calculate the crossing point, wether or not it is on the lines, and then check if it really is on both lines? My math lessons are quite far away now and I already struggled to understand how the code worked, but I think thats the way I would have coded it, naively...

**Comment by JinoBetti** [comment]
see fix in the following commit : https://github.com/JinoBetti/oripa/commit/8419155d012fae85af82d948961e60ff69900169 
I'll try to add unit tests before making a pull request

**Comment by Ooouch1** [comment]
Cool!
Good refactoring.

One suggestion: if you like to do test-driven development, first write tests and then change the product code.
I know it is difficult in many case of refactoring legacy code, though :)

**Comment by JinoBetti** [comment]
Yes that's what i want to achieve in the end, but since I don't know the code very well yet, I tend to fall back in my old demeanors... 
But hopefully I'll soon be able to add tests before refactoring ;)
